config/routes.rb
CATS::Application.routes.draw do
  resources :users

  resources :conditions

end

app/models/condition.rb
class Condition < ActiveRecord::Base

  # I'm not sure why this is necessary, but without this the ID ends up as a decimal
  # value instead of an integer.
  def to_param
    conditionid.to_i
  end

  # These are required because the CATS naming scheme is different from the standard
  # Rails naming scheme.
  set_table_name 'cats_condition'
  set_primary_key 'conditionid'
  set_sequence_name 'cats_conditionid'

  # Only the conditioncode and description fields are accessible to the user.
  attr_accessible :conditioncode, :description

  # Since data is always saved in uppercase, we want to convert the entered value to uppercase.
  # However, we want to do this before we check for the uniqueness of the conditioncode.
  # That's why it's in a before_validation callback.
  before_validation do
    self.conditioncode.upcase!
    self.description.upcase!
  end

  # These validations are the same as the ones in the database (validation trigger and
  # and unique index).  We are duplicating these here so that the user does not see the
  # Oracle error messages.

  # The conditioncode and description values are mandatory.
  validates_presence_of :conditioncode
  validates_presence_of :description

  # Verify that the conditioncode is unique
  validates_uniqueness_of :conditioncode

  # Since the fields in the database are only 50 characters long, prevent the user from
  # entering values longer than this.
  validates_length_of :conditioncode, :maximum => 50
  validates_length_of :description, :maximum => 50

end

app/models/user.rb
class User < ActiveRecord::Base

  # I'm not sure why this is necessary, but without this the ID ends up as a decimal
  # value instead of an integer.
  def to_param
    contactid.to_i
  end

  # These are required because the CATS naming scheme is different from the standard
  # Rails naming scheme.
  set_table_name 'cats_contact'
  set_primary_key 'contactid'
  set_sequence_name 'cats_contactid'

  #attr_accessible :active, :addcontactid, :adddttm, :address1, :address2, :address3, :approvercontactid, :approverdollars, :cellphone, :city, :contactcode, :contactid, :country, :department, :email, :faxphone, :firstname, :lastname, :locationdetailid, :locked, :managecontactid, :managedttm, :middlename, :mobilityversion, :orderdefaultid, :pagerphone, :password, :passwordchange, :phone, :postalcode, :securityprofileid, :stateprovince, :supervisorcontactid, :title, :url
  attr_accessible :active, :addcontactid, :adddttm, :address1, :address2, :address3, :approvercontactid, :cellphone, :city, :contactcode, :contactid, :country, :department, :email, :faxphone, :firstname, :lastname, :locationdetailid, :locked, :managecontactid, :managedttm, :middlename, :mobilityversion, :orderdefaultid, :pagerphone, :password, :passwordchange, :phone, :postalcode, :securityprofileid, :stateprovince, :supervisorcontactid, :title, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  include ApplicationHelper

  # GET /conditions
  # GET /conditions.json
  def index
    @conditions = Condition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conditions }
    end
  end

  # GET /conditions/1
  # GET /conditions/1.json
  def show
    @condition = Condition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @condition }
    end
  end

  # GET /conditions/new
  # GET /conditions/new.json
  def new
    @condition = Condition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @condition }
    end
  end

  # GET /conditions/1/edit
  def edit
    @condition = Condition.find(params[:id])
  end

  # POST /conditions
  # POST /conditions.json
  def create
    @condition = Condition.new(params[:condition])

    respond_to do |format|
      begin
        result = @condition.save
      rescue Exception => e
        # If an error occurred, pass the error message back to the user.
        @condition.errors.add(:conditionid, parse_error(e.message))
      end
      if result
        format.html { redirect_to @condition, notice: 'Condition was successfully created.' }
        format.json { render json: @condition, status: :created, location: @condition }

      else
        format.html { render action: "new" }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conditions/1
  # PUT /conditions/1.json
  def update
    @condition = Condition.find(params[:id])

    respond_to do |format|
      if @condition.update_attributes(params[:condition])
        format.html { redirect_to @condition, notice: 'Condition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conditions/1
  # DELETE /conditions/1.json
  def destroy
    @condition = Condition.find(params[:id])
    @condition.destroy

    respond_to do |format|
      format.html { redirect_to conditions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      begin
        result = @user.save
      rescue Exception => e
        # If an error occurred, pass the error message back to the user.
        @user.errors.add(:contactid, parse_error(e.message))
      end
      if result
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def parse_error(error_message)
    # If it's a CATS trigger error, then return only the CATS error.
    if error_message.index("ORA-20000:")
      start_position = error_message.index("ORA-20000:") + 10
      end_position = error_message.index("ORA-",start_position) - 1
      error_message[start_position..end_position]
    else
      # If it's not a CATS trigger error, then return the whole message.
      error_message
    end
  end
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conditions/_form.html.erb
<%= form_for(@condition) do |f| %>
  <% if @condition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@condition.errors.count, "error") %> prevented this record from being saved:</h2>

      <ul>
      <% @condition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Condition Code" %><br />
    <%= f.text_field :conditioncode %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conditions/edit.html.erb
<h1>Edit Condition</h1>

<%= render 'form' %>

<%= link_to 'Show', @condition %> |
<%= link_to 'Back', conditions_path %>

app/views/conditions/index.html.erb
<div id= "condition_list"
<h1>Conditions</h1>

<table>
  <tr>
    <th>Condition Code</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conditions.each do |condition| %>
  <tr class=" <%= cycle('list_line_odd' , 'list_line_even' ) %>" >
    <td><%= condition.conditioncode %></td>
    <td><%= condition.description %></td>
    <td><%= link_to 'Show', condition %></td>
    <td><%= link_to 'Edit', edit_condition_path(condition) %></td>
    <td><%= link_to 'Destroy', condition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>

<br />

<%= link_to 'New Condition', new_condition_path %>

app/views/conditions/new.html.erb
<h1>New condition</h1>

<%= render 'form' %>

<%= link_to 'Back', conditions_path %>

app/views/conditions/show.html.erb
<h1>Show Condition</h1>
<p id="notice"><%= notice %></p>

<table>
    <tr>
      <td><b>Conditioncode:</b></td>
      <td><%= @condition.conditioncode %></td>
    </tr>

    <tr>
      <td><b>Description:</b></td>
      <td><%= @condition.description %></td>
    </tr>
<table>

<%= link_to 'Edit', edit_condition_path(@condition) %> |
<%= link_to 'Back', conditions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CATS</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contactid %><br />
    <%= f.number_field :contactid %>
  </div>
  <div class="field">
    <%= f.label :contactcode %><br />
    <%= f.text_field :contactcode %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :middlename %><br />
    <%= f.text_field :middlename %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :securityprofileid %><br />
    <%= f.number_field :securityprofileid %>
  </div>
  <div class="field">
    <%= f.label :orderdefaultid %><br />
    <%= f.number_field :orderdefaultid %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :locked %><br />
    <%= f.text_field :locked %>
  </div>
  <div class="field">
    <%= f.label :passwordchange %><br />
    <%= f.text_field :passwordchange %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.text_field :active %>
  </div>
  <div class="field">
    <%= f.label :mobilityversion %><br />
    <%= f.text_field :mobilityversion %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :address3 %><br />
    <%= f.text_field :address3 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :stateprovince %><br />
    <%= f.text_field :stateprovince %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :postalcode %><br />
    <%= f.text_field :postalcode %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :cellphone %><br />
    <%= f.text_field :cellphone %>
  </div>
  <div class="field">
    <%= f.label :pagerphone %><br />
    <%= f.text_field :pagerphone %>
  </div>
  <div class="field">
    <%= f.label :faxphone %><br />
    <%= f.text_field :faxphone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :locationdetailid %><br />
    <%= f.number_field :locationdetailid %>
  </div>
  <div class="field">
    <%= f.label :supervisorcontactid %><br />
    <%= f.number_field :supervisorcontactid %>
  </div>
  <div class="field">
    <%= f.label :approvercontactid %><br />
    <%= f.number_field :approvercontactid %>
  </div>
  <!--<div class="field">-->
    <%# f.label :approverdollars %>
    <!--<%# f.text_field :approverdollars %>-->
  <!--</div>-->
  <div class="field">
    <%= f.label :addcontactid %><br />
    <%= f.number_field :addcontactid %>
  </div>
  <div class="field">
    <%= f.label :adddttm %><br />
    <%= f.datetime_select :adddttm %>
  </div>
  <div class="field">
    <%= f.label :managecontactid %><br />
    <%= f.number_field :managecontactid %>
  </div>
  <div class="field">
    <%= f.label :managedttm %><br />
    <%= f.datetime_select :managedttm %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Contactid</th>
    <th>Contactcode</th>
    <th>Firstname</th>
    <th>Middlename</th>
    <th>Lastname</th>
    <th>Title</th>
    <th>Department</th>
    <th>Securityprofileid</th>
    <th>Orderdefaultid</th>
    <th>Password</th>
    <th>Locked</th>
    <th>Passwordchange</th>
    <th>Active</th>
    <th>Mobilityversion</th>
    <th>Address1</th>
    <th>Address2</th>
    <th>Address3</th>
    <th>City</th>
    <th>Stateprovince</th>
    <th>Country</th>
    <th>Postalcode</th>
    <th>Phone</th>
    <th>Cellphone</th>
    <th>Pagerphone</th>
    <th>Faxphone</th>
    <th>Email</th>
    <th>Url</th>
    <th>Locationdetailid</th>
    <th>Supervisorcontactid</th>
    <th>Approvercontactid</th>
    <!--<th>Approverdollars</th>-->
    <th>Addcontactid</th>
    <th>Adddttm</th>
    <th>Managecontactid</th>
    <th>Managedttm</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= user.contactid %></td>
        <td><%= user.contactcode %></td>
        <td><%= user.firstname %></td>
        <td><%= user.middlename %></td>
        <td><%= user.lastname %></td>
        <td><%= user.title %></td>
        <td><%= user.department %></td>
        <td><%= user.securityprofileid %></td>
        <td><%= user.orderdefaultid %></td>
        <td><%= user.password %></td>
        <td><%= user.locked %></td>
        <td><%= user.passwordchange %></td>
        <td><%= user.active %></td>
        <td><%= user.mobilityversion %></td>
        <td><%= user.address1 %></td>
        <td><%= user.address2 %></td>
        <td><%= user.address3 %></td>
        <td><%= user.city %></td>
        <td><%= user.stateprovince %></td>
        <td><%= user.country %></td>
        <td><%= user.postalcode %></td>
        <td><%= user.phone %></td>
        <td><%= user.cellphone %></td>
        <td><%= user.pagerphone %></td>
        <td><%= user.faxphone %></td>
        <td><%= user.email %></td>
        <td><%= user.url %></td>
        <td><%= user.locationdetailid %></td>
        <td><%= user.supervisorcontactid %></td>
        <td><%= user.approvercontactid %></td>
        <!--<td><%#user.approverdollars %></td>-->
        <td><%= user.addcontactid %></td>
        <td><%= user.adddttm %></td>
        <td><%= user.managecontactid %></td>
        <td><%= user.managedttm %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contactid:</b>
  <%= @user.contactid %>
</p>

<p>
  <b>Contactcode:</b>
  <%= @user.contactcode %>
</p>

<p>
  <b>Firstname:</b>
  <%= @user.firstname %>
</p>

<p>
  <b>Middlename:</b>
  <%= @user.middlename %>
</p>

<p>
  <b>Lastname:</b>
  <%= @user.lastname %>
</p>

<p>
  <b>Title:</b>
  <%= @user.title %>
</p>

<p>
  <b>Department:</b>
  <%= @user.department %>
</p>

<p>
  <b>Securityprofileid:</b>
  <%= @user.securityprofileid %>
</p>

<p>
  <b>Orderdefaultid:</b>
  <%= @user.orderdefaultid %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Locked:</b>
  <%= @user.locked %>
</p>

<p>
  <b>Passwordchange:</b>
  <%= @user.passwordchange %>
</p>

<p>
  <b>Active:</b>
  <%= @user.active %>
</p>

<p>
  <b>Mobilityversion:</b>
  <%= @user.mobilityversion %>
</p>

<p>
  <b>Address1:</b>
  <%= @user.address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @user.address2 %>
</p>

<p>
  <b>Address3:</b>
  <%= @user.address3 %>
</p>

<p>
  <b>City:</b>
  <%= @user.city %>
</p>

<p>
  <b>Stateprovince:</b>
  <%= @user.stateprovince %>
</p>

<p>
  <b>Country:</b>
  <%= @user.country %>
</p>

<p>
  <b>Postalcode:</b>
  <%= @user.postalcode %>
</p>

<p>
  <b>Phone:</b>
  <%= @user.phone %>
</p>

<p>
  <b>Cellphone:</b>
  <%= @user.cellphone %>
</p>

<p>
  <b>Pagerphone:</b>
  <%= @user.pagerphone %>
</p>

<p>
  <b>Faxphone:</b>
  <%= @user.faxphone %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Url:</b>
  <%= @user.url %>
</p>

<p>
  <b>Locationdetailid:</b>
  <%= @user.locationdetailid %>
</p>

<p>
  <b>Supervisorcontactid:</b>
  <%= @user.supervisorcontactid %>
</p>

<p>
  <b>Approvercontactid:</b>
  <%= @user.approvercontactid %>
</p>

<!--<p>-->
  <!--<b>Approverdollars:</b>-->
  <!--<%# @user.approverdollars %>-->
<!--</p>-->

<p>
  <b>Addcontactid:</b>
  <%= @user.addcontactid %>
</p>

<p>
  <b>Adddttm:</b>
  <%= @user.adddttm %>
</p>

<p>
  <b>Managecontactid:</b>
  <%= @user.managecontactid %>
</p>

<p>
  <b>Managedttm:</b>
  <%= @user.managedttm %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>